<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7695d6c4-ad37-4593-80e1-4a80d0411ba1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="QuestPDF" Version="2026.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoldenPappadam.Infrastructure\GoldenPappadam.Infrastructure.csproj" />
    <ProjectReference Include="..\GoldenPappadam.Domain\GoldenPappadam.Domain.csproj" />
  </ItemGroup>

</Project>
